### PR TITLE
Simplify 2D meshgrid.

### PR DESCRIPTION
**Pull request by pkofod**

### CODE REVIEW

**Comment by pkofod** [comment]
I guess you could even "one line" it, but that line would get quite long!

**Comment by tawheeler** [comment]
Thank you for submitting a PR!
Is there a performance difference?

**Comment by pkofod** [comment]
It seems there is

```julia
using Benchmarks

function meshgrid_old{T}(vx::AbstractVector{T}, vy::AbstractVector{T})
    m, n = length(vy), length(vx)
    vx = reshape(vx, 1, n)
    vy = reshape(vy, m, 1)
    (repmat(vx, m, 1), repmat(vy, 1, n))
end

function meshgrid{T}(vx::AbstractVector{T}, vy::AbstractVector{T})
    (T[i for j in vy, i in vx], T[j for j in vy, i in vx])
end

a = -10:10
b = -10:10

@benchmark meshgrid_old(a, b)
================ Benchmark Results ========================
     Time per evaluation: 6.75 μs [6.56 μs, 6.93 μs]
Proportion of time in GC: 0.00% [0.00%, 0.00%]
        Memory allocated: 10.38 kb
   Number of allocations: 95 allocations
       Number of samples: 2401
   Number of evaluations: 18901
         R² of OLS model: 0.952
 Time spent benchmarking: 1.34 s


@benchmark meshgrid(a, b)
================ Benchmark Results ========================
     Time per evaluation: 1.33 μs [1.31 μs, 1.35 μs]
Proportion of time in GC: 6.24% [5.22%, 7.26%]
        Memory allocated: 7.09 kb
   Number of allocations: 3 allocations
       Number of samples: 8201
   Number of evaluations: 4959001
         R² of OLS model: 0.951
 Time spent benchmarking: 10.47 s


a = -100:100
b = -100:100

@benchmark meshgrid_old(a, b)
================ Benchmark Results ========================
     Time per evaluation: 161.37 μs [107.64 μs, 215.09 μs]
Proportion of time in GC: 1.31% [0.00%, 6.84%]
        Memory allocated: 660.28 kb
   Number of allocations: 817 allocations
       Number of samples: 100
   Number of evaluations: 100
 Time spent benchmarking: 0.12 s


@benchmark meshgrid(a, b)
================ Benchmark Results ========================
     Time per evaluation: 81.50 μs [43.54 μs, 119.45 μs]
Proportion of time in GC: 1.48% [0.00%, 7.75%]
        Memory allocated: 631.44 kb
   Number of allocations: 5 allocations
       Number of samples: 100
   Number of evaluations: 100
 Time spent benchmarking: 0.11 s

 
 a = -1000:1000
 b = -1000:1000

 @benchmark meshgrid_old(a, b)
 ================ Benchmark Results ========================
     Time per evaluation: 17.95 ms [2.65 ms, 33.24 ms]
Proportion of time in GC: 5.03% [4.47%, 5.58%]
        Memory allocated: 61.37 mb
   Number of allocations: 8023 allocations
       Number of samples: 59
   Number of evaluations: 59
 Time spent benchmarking: 1.25 s


 
 @benchmark meshgrid(a, b)
 ================ Benchmark Results ========================
      Time per evaluation: 7.84 ms [7.59 ms, 8.09 ms]
 Proportion of time in GC: 9.13% [8.84%, 9.42%]
         Memory allocated: 61.10 mb
    Number of allocations: 5 allocations
        Number of samples: 100
    Number of evaluations: 100
  Time spent benchmarking: 0.90 s


```

**Comment by tawheeler** [comment]
Perfect, thanks.

**Pull request merged**
