### PR TITLE
Label style options and reset methods for options

### PR DESCRIPTION
**Pull request by fredrikekre**
- Added `xlabelStyle`, `ylabelStyle` and `zlabelStyle` keywords, which can be used to e.g. rotate and move the labels
- Added reset methods to fully reset `PGFPlotsOptions` and `PGFPlotsPreamble`, only the latest added option could be removed before, using the `pop!` functions.
- Updated docs with these changes

Note that I did not run the notebook, since that would credit me with thousands of lines. I can of course run it and push if it is desired.

### CODE REVIEW

**Comment by mykelk** [comment]
Nice! But it seems that the desired effect is not seen in the documentation for the ylabelStyle:
image
Right?

**Comment by mykelk** [comment]
Oh, is it because you didn't run the notebook (as you mentioned)? I'm fine with you doing that.

**Comment by fredrikekre** [comment]
Okay, I will run it and push again. Also added documentation about the reset functions and the option to ignore the preamble when saving to `.tex`

**Comment by fredrikekre** [comment]
There we go!

ylabel

**Comment by mykelk** [comment]
Thanks!

**Pull request merged**
