### PR TITLE
Updated tuple syntax

### PR DESCRIPTION
**Pull request by dgleich**
I needed to change the syntax for tuples to get this to work on 

Julia Version 0.4.0-dev+5511
Commit 1e081b7* (2015-06-22 05:05 UTC)

### CODE REVIEW

**Comment by mykelk** [comment]
Nice. But would it be possible to use [Compat.jl](https://github.com/JuliaLang/Compat.jl) for the tuple types so that we preserve compatibility for 0.3? Since 0.4 isn't released yet, I wouldn't want to break it for the 0.3 users.

**Comment by dgleich** [comment]
Take a look ... do you know of a way to avoid defining RealRange twice? I didn't think that should be exported.

**Comment by mykelk** [comment]
Not sure how to get around not defining it twice, but what you have works. So, I'll merge it.

**Comment by mykelk** [comment]
Thanks for your contribution, by the way.

**Pull request merged**
